 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/diaries", type: :request do
  # Diary. As you add validations to Diary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Diary.create! valid_attributes
      get diaries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      diary = Diary.create! valid_attributes
      get diary_url(diary)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_diary_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      diary = Diary.create! valid_attributes
      get edit_diary_url(diary)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Diary" do
        expect {
          post diaries_url, params: { diary: valid_attributes }
        }.to change(Diary, :count).by(1)
      end

      it "redirects to the created diary" do
        post diaries_url, params: { diary: valid_attributes }
        expect(response).to redirect_to(diary_url(Diary.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Diary" do
        expect {
          post diaries_url, params: { diary: invalid_attributes }
        }.to change(Diary, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post diaries_url, params: { diary: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested diary" do
        diary = Diary.create! valid_attributes
        patch diary_url(diary), params: { diary: new_attributes }
        diary.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the diary" do
        diary = Diary.create! valid_attributes
        patch diary_url(diary), params: { diary: new_attributes }
        diary.reload
        expect(response).to redirect_to(diary_url(diary))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        diary = Diary.create! valid_attributes
        patch diary_url(diary), params: { diary: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested diary" do
      diary = Diary.create! valid_attributes
      expect {
        delete diary_url(diary)
      }.to change(Diary, :count).by(-1)
    end

    it "redirects to the diaries list" do
      diary = Diary.create! valid_attributes
      delete diary_url(diary)
      expect(response).to redirect_to(diaries_url)
    end
  end
end
