 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/parises", type: :request do
  # Parise. As you add validations to Parise, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Parise.create! valid_attributes
      get parises_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      parise = Parise.create! valid_attributes
      get parise_url(parise)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_parise_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      parise = Parise.create! valid_attributes
      get edit_parise_url(parise)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Parise" do
        expect {
          post parises_url, params: { parise: valid_attributes }
        }.to change(Parise, :count).by(1)
      end

      it "redirects to the created parise" do
        post parises_url, params: { parise: valid_attributes }
        expect(response).to redirect_to(parise_url(Parise.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Parise" do
        expect {
          post parises_url, params: { parise: invalid_attributes }
        }.to change(Parise, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post parises_url, params: { parise: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested parise" do
        parise = Parise.create! valid_attributes
        patch parise_url(parise), params: { parise: new_attributes }
        parise.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the parise" do
        parise = Parise.create! valid_attributes
        patch parise_url(parise), params: { parise: new_attributes }
        parise.reload
        expect(response).to redirect_to(parise_url(parise))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        parise = Parise.create! valid_attributes
        patch parise_url(parise), params: { parise: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested parise" do
      parise = Parise.create! valid_attributes
      expect {
        delete parise_url(parise)
      }.to change(Parise, :count).by(-1)
    end

    it "redirects to the parises list" do
      parise = Parise.create! valid_attributes
      delete parise_url(parise)
      expect(response).to redirect_to(parises_url)
    end
  end
end
